DO $$
BEGIN
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'municipios') THEN
	CREATE TABLE MUNICIPIOS
	(
		MUN_CODIGO SERIAL,
		MUN_NOMBRE VARCHAR(100) NOT NULL,
        DEP_CODIGO INT NOT NULL,
		CONSTRAINT PK_MUNICIPIOS PRIMARY KEY(MUN_CODIGO),
        CONSTRAINT FK_MUNICIPIOS_DEPARTAMENTOS FOREIGN KEY (DEP_CODIGO) REFERENCES DEPARTAMENTOS (DEP_CODIGO)
	);
	RAISE NOTICE 'SE HA CREADO LA TABLA MUNICIPIOS';
END IF;
END $$;