DO $$
BEGIN
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'clientes') THEN
	CREATE TABLE CLIENTES
	(
		CLI_CODIGO SERIAL,
		CLI_NOMBRECOMPLETO VARCHAR(180) NOT NULL,
        CLI_CORREO VARCHAR(45) NOT NULL,
        CLI_CELULAR VARCHAR(10) NOT NULL,
		CONSTRAINT PK_CLIENTES PRIMARY KEY(CLI_CODIGO)
	);
	RAISE NOTICE 'SE HA CREADO LA TABLA CLIENTES';
END IF;
END $$;