DO $$
BEGIN
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'cotizaciones') THEN
	CREATE TABLE COTIZACIONES
	(
		COT_CODIGO SERIAL,
		COT_ESTADO INT NOT NULL,
		COT_FECHA DATE NOT NULL,
		CLI_CODIGO INT NOT NULL,
        MUN_CODIGO INT NOT NULL,
        API_MODELO VARCHAR(45) NOT NULL,
		CONSTRAINT PK_COTIZACIONES PRIMARY KEY(COT_CODIGO),
        CONSTRAINT FK_COTIZACIONES_CLIENTES FOREIGN KEY (CLI_CODIGO) REFERENCES CLIENTES (CLI_CODIGO),
        CONSTRAINT FK_COTIZACIONES_MUNICIPIOS FOREIGN KEY (MUN_CODIGO) REFERENCES MUNICIPIOS (MUN_CODIGO)
	);
	RAISE NOTICE 'SE HA CREADO LA TABLA COTIZACIONES';
END IF;
END $$;