DO $$
BEGIN
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'receptores') THEN
	CREATE TABLE RECEPTORES
	(
		REC_CODIGO SERIAL,
		REC_CORREO VARCHAR(45) NOT NULL,
		CONSTRAINT PK_RECEPTORES PRIMARY KEY(REC_CODIGO)
	);
	RAISE NOTICE 'SE HA CREADO LA TABLA RECEPTORES';
END IF;
END $$;